### ISSUE TITLE
UI stuck when resuming app on Android 14 (Specially Samsung)

### ISSUE THREAD

**Issue by Aaniket7** [anandnet/Harmony-Music#138]
I'm using samsung M34 5g ..
The device is currently running on Android 14 (One UI 6.0)
The UI of this app is lagging or hanging in between, and sometimes the songs are also stopping abruptly. 
Plz fix these issues..

**Comment by anandnet** [comment]
Please enable ignore battery battery optimization from settings & let me know if this fixes this issue.

**Comment by Aaniket7** [comment]
Just tried, but still not working.

**Comment by anandnet** [comment]
Need to check, bcz i haven't tested on android 14 devices yet. Thanks for reporting.

**Comment by Aaniket7** [comment]
Ok, let me know.
And plz make it stable and compatible with latest android
versions...especially with samsung one ui..thankYou

**Comment by anandnet** [comment]
Ui stuck/getting blank screen on resuming this app, right? Seems there is some issue with flutter (tech, this app is built on) you may check this issue https://github.com/flutter/flutter/issues -> <b>#139630 : Samsung phones running Android 14 stops drawing entire app on resume</b>, Unfortunatly we will have to wait untill this issue has some fix from flutter side.

**Comment by Aaniket7** [comment]
Ok, I will wait.

**Comment by salandreika87** [comment]
using s23 ultra. the UI didnt stuck yet but the animations are chunky, like there is no GPU HW accelleration enabled. thanks for giving us the option to disable animation. however, please make the UI animations more smooth and non-linear.

**Comment by godslayer007** [comment]
Yes I am having the same problem

**Comment by anandnet** [comment]
This has been fixed now, may occur but very rare.

**Comment by godslayer007** [comment]
Thanks

**Comment by Aaniket7** [comment]
> This has been fixed now, may occur but very rare.

Nothing's changed...it still freezing on the quick picks
On samsung m34 5g 
Android 14
One ui 6.1
App version 1.10.0
Plz fix this

https://github.com/user-attachments/assets/23988ab9-0fae-4c70-b22e-6006b67660d5

https://github.com/user-attachments/assets/303e926a-2479-49e8-b849-53a5b9b55602

**Comment by anandnet** [comment]
This is disappointing 😞, is it happening every time?, i am also using samsung device f35 this whole time for debugging purpose but now this issue occurance is very rare. Flutter has also confirmed this issue has been fixed. Do you have any steps to repoduce this issue? May be you can try fresh install , if you have to save playlists you can backup app data.

**Comment by Aaniket7** [comment]
Everytime this is happening

**Comment by Aaniket7** [comment]
> This is disappointing 😞, is it happening every time?, i am also using samsung device f23 this whole time for debugging purpose but now this issue occurance is very rare. Flutter has also confirmed this issue has been fixed. Do you have any steps to repoduce this issue? May be you can try fresh install , if you have to save playlists you can backup app data.

Everytime this is happening.
