### ISSUE TITLE
Song is not playable due to server restriction!

### ISSUE THREAD

**Issue by 60d74** [anandnet/Harmony-Music#295]
**Describe the bug**
Songs are not playing due to server restrictions. This happens with all songs, both with age restrictions and without.

**To Reproduce**
1. Try to play the song.
2. See error

**Expected behavior**
The song is playing.

**Screenshots**
<details>
  <summary>Screenshot and recording</summary>

![Screenshot_20241007-115239](https://github.com/user-attachments/assets/2ff044ee-5e49-4de8-8bf2-09dd5d05a1cf)

https://github.com/user-attachments/assets/0141b68f-6dd9-4555-9087-cfcbfcc1b917

</details>

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android 14

**Additional context**
This happens with all forks of ViMusic. I tried changing the streaming quality, change/disable VPN, but nothing worked.

**Comment by anandnet** [comment]
could you please check whether ytm is working fine for you or not?

**Comment by 60d74** [comment]
also, the removed songs are played as well since i use a non-US VPN

**Comment by 60d74** [comment]
in yt music, i mean

**Comment by 60d74** [comment]
in yt music, i mean

**Comment by 60d74** [comment]
no, still the same with latest github ver

**Comment by 60d74** [comment]
i noticed that piped clients such as libre are not working too

**Comment by andreatede2002** [comment]
I have the same issue!

**Comment by jacobot1** [comment]
Same issue here. No songs whatsoever will play. I even tried Spotube. Same result.

**Comment by Elnachoenojado** [comment]
Hola, tengo es mismo problema, podrían decirme cómo solucionarlo? Ahora no puedo reproducir ninguna canción en español, me gustaría también sacarle la restricción para menores ya que soy mayor.

**Comment by Hagen77** [comment]
Good evening,
I downloaded the newest version today. It worked for 10 minutes and now I get the SONG IS NOT PLAYABLE DUE TO SERVER RESTRICTION! message when I try to play any song.

Thank you.

**Comment by andreatede2002** [comment]
Strangely, since this morning the application has started working again, and the music plays without any issues.

**Comment by A-J-Mortimer** [comment]
Same here, Can´t play  anything

**Comment by anandnet** [comment]
Thanks all for reporting, Will release a new version with available solution.

**Comment by andreatede2002** [comment]
> Thanks all for reporting, Will release a new version with available solution.

Thanks for the quick response regarding the bug with the songs not playing due to server restrictions.

I’m curious about what might have caused this issue. Are there any ways to create self-correcting code or automatic fixes for problems like this? If that's feasible, I’d be interested to know how challenging or costly it might be to implement.

I don’t have a background in computer science, so I appreciate any insights you can share. Thank you for your work on this.

**Comment by Hagen77** [comment]
NEWSFLASH!

It's alive!!!

The app works now.

Thank you. Have a happy weekend!

**Comment by anandnet** [comment]
if anyone can build and test, that would be be realy helpful for me. I am not able to test because this issue is not appearing/coming for me. i've made some changes that would probably prevent this error.

Building apk steps:
-------------------
Fork repo https://github.com/anandnet/build-HM and follow steps mentioned in description.
or 
if https://github.com/anandnet/build-HM/actions/runs/11297116437 it is accessible to you, you can download artifacts and test.

Please take a backup of data if you have some playlists or bookmarks.

**Comment by jacobot1** [comment]
> if anyone can build and test, that would be be realy helpful for me. I am not able to test because this issue is not appearing/coming for me. i've made some changes that would probably prevent this error.
> 
> Building apk steps:
> -------------------
> Fork repo https://github.com/anandnet/build-HM and follow steps mentioned in description.
> or 
> if https://github.com/anandnet/build-HM/actions/runs/11297116437 it is accessible to you, you can download artifacts and test.
> 
> Please take a backup of data if you have some playlists or bookmarks.
> 

It seems to be working now, though the song loading seems just slightly slower (not by much). Will continue to use throughout the day and confirm.

**Comment by andreatede2002** [comment]
> if anyone can build and test, that would be be realy helpful for me. I am not able to test because this issue is not appearing/coming for me. i've made some changes that would probably prevent this error.
> 
> ## apk building steps:
> Fork repo https://github.com/anandnet/build-HM and follow steps mentioned in description. or if https://github.com/anandnet/build-HM/actions/runs/11297116437 it is accessible to you, you can download artifacts and test.
> 
> Please take a backup of data if you have some playlists or bookmarks.

Hi, i dont know how this testing process works, but as you probably know, the issue is not only on PC version but also on android, so if you release a temporary apk i can help you testing the app too! Thank you in advance

**Comment by jacobot1** [comment]
> Hi, i dont know how this testing process works, but as you probably know, the issue is not only on PC version but also on android, so if you release a temporary apk i can help you testing the app too! Thank you in advance

The android apk is included in the build as I was able to download it. Should be in the Artifacts section.

**Comment by Adrielsoto22** [comment]
How to fix this but?

**Comment by anandnet** [comment]
> if anyone can build and test, that would be be realy helpful for me. I am not able to test because this issue is not appearing/coming for me. i've made some changes that would probably prevent this error.
> 
> apk building  steps:
> -------------------
> Fork repo https://github.com/anandnet/build-HM and follow steps mentioned in description.
> or 
> if https://github.com/anandnet/build-HM/actions/runs/11297116437 it is accessible to you, you can download artifacts and test.
> 
> Please take a backup of data if you have some playlists or bookmarks.
> 

@Adrielsoto22 , you can test it  and let me know, if this works i'll release new version.

**Comment by 60d74** [comment]
sadly, this doesn't work for me, i'm still getting an error.

**Comment by jacobot1** [comment]
@anandnet I have not had any issues since I installed the new test version you sent out yesterday.

**Comment by kr0fff** [comment]
The same issue as here

**Comment by andreatede2002** [comment]
> > Hi, i dont know how this testing process works, but as you probably know, the issue is not only on PC version but also on android, so if you release a temporary apk i can help you testing the app too! Thank you in advance
> 
> The android apk is included in the build as I was able to download it. Should be in the Artifacts section.

Thank you! I installed the apk ok my redmi and it works fine for me now 😁😉 i'll keep using this version and if It stops working again i'll let you know

**Comment by Adrielsoto22** [comment]
Ya he encontrado la solución

**Comment by Adrielsoto22** [comment]
(funciona en Android) primero vas a descargar una aplicación llamada rar, después en estas publicaciones hay una publicación del usuario llamado anandet (el creador de la app) y tiene un apartado que dice pasos para crear el APK pulsa el segundo link y te va a llevar a otra página donde vas a descargar la app ya que descargues el archivo vas a ir a la aplicación rar y abres el archivo en esa aplicación ya que lo abras van a aparecer tres opciones de APK abres la que tiene más megabytes y después lo va a extraer esa aplicación sola el archivo y lo instalas y listo

**Comment by nettuno3** [comment]
I solved it for now with VPN on Switzerland

**Comment by anandnet** [comment]
As per @jacobot1 and @Adrielsoto22's confirmation. I've released a new version. Try this one.

**Comment by nettuno3** [comment]
Perfect!! Works great even without VPN. Thanks 

Il giorno 13 ott 2024, 11:16, alle ore 11:16, anandnet ***@***.***> ha scritto:

**Comment by 60d74** [comment]
still getting the same error even with the latest version
<details>
  <summary>Spoiler</summary>
  
  
![Screenshot_20241013-193705](https://github.com/user-attachments/assets/ed6b3489-624a-44ee-aa80-1a9f306d5d78)
![Screenshot_20241013-193713](https://github.com/user-attachments/assets/50a73562-d02e-4b7d-8c55-019a3f257494)

</details>

**Comment by nettuno3** [comment]
Do you have VPN active?

Il giorno 13 ott 2024, 11:40, alle ore 11:40, mike oxmaul ***@***.***> ha scritto:

**Comment by anandnet** [comment]
> still getting the same error even with the latest version
> <details>
>   <summary>Spoiler</summary>
>   
>   
> ![Screenshot_20241013-193705](https://github.com/user-attachments/assets/ed6b3489-624a-44ee-aa80-1a9f306d5d78)
> ![Screenshot_20241013-193713](https://github.com/user-attachments/assets/50a73562-d02e-4b7d-8c55-019a3f257494)
> 
> </details>

Please try without vpn.

**Comment by 60d74** [comment]
> Please try without vpn.

I tried different protocols and locations, but I can't try without because YouTube is blocked in my country.

**Comment by nettuno3** [comment]
I understand, I worked with VPN in Switzerland. With Windscribe VPN app

Il giorno 13 ott 2024, 12:15, alle ore 12:15, mike oxmaul ***@***.***> ha scritto:

**Comment by anandnet** [comment]
Oh, okay. You may try other foss clients but i believe you will face the same problem with vpn. Seems yt has already tracked vpn IPs to prevent the misuse. Perhaps you have already felt the similar issues with the proxy based yt client ie..Piped

**Comment by diogopessoa** [comment]
With the new update (1.10.2) the bug has been fixed! 👏

**Comment by shubhamsutar2** [comment]
This issue still exists for many songs.
v1.10.31

**Comment by anandnet** [comment]
> This issue still exists for many songs. v1.10.31

You should try now.

**Comment by anandnet** [comment]
closing this, you can follow #396

**Comment by ArthurGuerrier** [comment]
Parreil !
