### ISSUE TITLE
Audio from the music video plays, not audio from the link which has just audio

### ISSUE THREAD

**Issue by superpoincare** [anandnet/Harmony-Music#439]
YT Music for non-premium users plays audio from the music video if there is one. But lots of times, the audio in the music video is different from the one with just audio. For premium users, YT Music plays the original audio.

Now, other apps like NewPipe try to get around this, and access the audio-only URL. I don't know if you player had this feature before but you could try this.

**Comment by anandnet** [comment]
i think i have fixed it, do you have any example so that i can verify it?

**Comment by anandnet** [comment]
This has been fixed now in new version.

**Comment by JoeneckSpoeneck** [comment]
Hm, for me the issue still persists. I'm on the newest version (v1.11.2) and use the AppImage on Linux, could that be the cause? For example, if you start the song "Lone Digger" by Caravan Palace in the Album, it plays the audio of the music video, which is completely different than the audio of the only audio song. I also tested it on my Android Smartphone and there the issue is also present.
